name: Bug Report
description: 🐛 File a bug report
title: "[🐛 BUG]: "
labels: ["B-bug", "F-need-verification"]
assignees:
  - butschster
  - roxblnfk
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: checkboxes
    id: search-done
    attributes:
      label: No duplicates 🥲.
      options:
        - label: I have searched for a similar issue in our bug tracker and didn't find any solutions.
          required: true
          
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
      
  - type: textarea
    id: version
    attributes:
      label: Version (package version)
      description: What version of our software are you running?
      placeholder: x.x.x
    validations:
      required: true
      
  - type: textarea
    id: repro
    attributes:
      label: How to reproduce the issue?
      description: .rr.yaml, rr version and steps on how to reproduce the issue?
    validations:
      required: true
      
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
